### ISSUE TITLE
Navigation state stack influences display incorrectly

### ISSUE THREAD

**Issue by eaceaser** [fauna/dashboard#40]
Minor issue, both Class and Index are marked as selected.

![screenshot_20170103_163325](https://cloud.githubusercontent.com/assets/157866/21628202/78e126a2-d1d2-11e6-9a4b-cdf349f822e6.png)

**Comment by eaceaser** [comment]
Looks like this is a general issue, I've seen it by navigating to another page not through these buttons, like navigating to the 'database' page by clicking the breadcrumb at the bottom.

**Comment by jchris** [comment]
There are some of the links that try to introspect on themselves to see if they are the current target. But it only happens when they are drawn, so when some other link is followed that doesn't redraw them, they stay highlighted. I haven't decided yet if it's confusing or useful. In jQuery it'd be an easy fix. ;)

**Comment by eaceaser** [comment]
imo its a bit confusing because theres no way to really know where you're actually at and if clicking things that are lit up will have an effect. if we expect to be able to navigate up and down the UI stack we should move that into a some kind of breadcrumb-style thingy too, or just rely on forward/back browser history navigation

**Comment by marrony** [comment]
With new dashboard this is not happening anymore

**Comment by erickpintor** [comment]
Fixed.
