### ISSUE TITLE
standardize Component file-tree structure

### ISSUE THREAD

**Issue by jchris** [fauna/dashboard#43]
As we convert components to redux, we should rename their main file to `index.js`.

We should also split out components that are currently in their own module to separate modules, so the actions / reducers are easy to track.

**Comment by jchris** [comment]
We've made good progress, maybe we want to split out `components` and `lib` in the `src` directory.

**Comment by marrony** [comment]
What do you guys think about this?

<img width="213" alt="screen shot 2017-01-12 at 8 30 39 pm" src="https://cloud.githubusercontent.com/assets/1334759/21911089/2798adc0-d906-11e6-895d-21b0ae80bd41.png">

`components` folder has all react components, it only render based on its props/state. Also every action is based on callbacks passed through props and know nothing about redux

`classes.js` (in that case) has all actions and reducers

`containers.js` is where we `connect()` react components with redux. Also is where we map our state to properties

`index.js` is only to export the necessary classes/functions to external world

**Comment by jchris** [comment]
maybe `containers` -> `connectors` ?

**Comment by jchris** [comment]
or the connect calls could also go in the `classes.js` and we could call it `redux.js`

**Comment by marrony** [comment]
as is today `index.js` has all actions and reducers and it's already large, if we put connect calls there (and rename to `redux.js`) it will became even larger

**Comment by erickpintor** [comment]
> components folder has all react components, it only render based on its props/state. Also every action is based on callbacks passed through props and know nothing about redux

Why do you think we need to break the dependency between components and redux?

That seems like a lot to worry about considering that redux actions are safe to throw around since the reducers should always keep the state consistent.

I'm asking mostly because we need to get a pattern to apply at the whole codebase. The approach I was following so far is:
- Components receive state via `connect` from `react-redux`;
- Components react on changes on redux state;
- Components dispatch actions in response to user interactions;
- Reducers makes the required changes upon triggered actions;
- The whole app just updates itself.

The rest is fine to me.

**Comment by jchris** [comment]
As far as splitting things up, I like splitting the components individually, I'm not sure yet how much of the actions and reducers are shared among components, but shared stuff should go in another file, something similar to what we have here.

Maybe we don't need to lock it down 100% now, so much as decide what we are optimizing on (don't want to click too many places to follow something) or do we like having actions in one file and components in another so they can be in a two panel editor? etc.

**Comment by erickpintor** [comment]
I've been experiencing a nice flow when we put actions and reducers in the `index.js` file for each module and the components in another. For example:

```js
import { Notification, NotificationType, pushNotification } from "/notification"
```

We can use the above import in places where only refer to the notification center behavior and:

```js
import NotificationBar from "/notification/NotificationBar"
```

when you need a ui component.

**Comment by erickpintor** [comment]
Currently, they are all implemented in the following pattern:

```
- [module name]/
  - __tests__/: unit tests for the module
  - components/: react components related to this module
  - [file name].js: one or more files to implement the business logic
  - index.js: it exposes module's public interface
```

We always import functions from modules instead of files. For example:
```
import { monitorActivity } from "./activity-monitor"
```

Imports are organized as:
- Library default imports, like: `import React from "react"`
- Library non default imports, like: `import { connect } from "react-redux"
- Empty line
- Own code imports

External services are located at `external` module. Right now we only have Intercom.
Persistence code, including a wrapper to faunadb client, is located at `persistence` module.
